### ISSUE TITLE
Doesn't work for YELLOW enemies

### ISSUE THREAD

**Issue by gochev** [Xruptor/xanShadowBurn#1]
It turns out it doesnt work on a yellow enemies because the function is it an enemy is false.

Notes: I used on version 6.2

**Comment by Xruptor** [comment]
Hmm yellow enemies.  Can you explain this?  Are they neutral enemies?  Normally it's Red for a target you can attack.  I'm assuming you are working on grinding reputation enemies that are yellow?  Please provide a bit more on where and how to replicate this.  It should be a simple fix.  There is a short delay checker in the code as well to prevent spamming it on the same monster.  This only occurs when you switch targets.
